regions:
  - ap-south-1
  - global

blocklist:
<<<<<<< HEAD
  - "880690594512"  # management account ID
=======
  - "880690594512"  # Replace with your management account ID
>>>>>>> 3e683df (Version 1)

accounts:
  "070640552464":
    filters:
      IAMRole:
        - "OrganizationAccountAccessRole"
      IAMRolePolicyAttachment:
        - "OrganizationAccountAccessRole -> AdministratorAccess"
      IAMRolePolicy:
        - property: role
          value: "OrganizationAccountAccessRole"
      IAMPolicy:
        - "arn:aws:iam::070640552464:policy/CoderCreatedIdentityBoundary"
        - "arn:aws:iam::070640552464:policy/DefaultIamPolicy"